# conda env create --file environment.yml
name: mapa_v2
channels:
  - anaconda
  - defaults
dependencies:
  - pip
  - python=3.11.3
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - plotly
  - seaborn
    
